// Generated by CoffeeScript 1.12.4
var errors;

module.exports = function() {
  var Module;
  Module = lotus.Module;
  log.moat(1);
  log.white("Crawling: ");
  log.yellow(lotus.path);
  log.moat(1);
  Module.watch(lotus.path, {
    add: function(mod) {
      return mod.load(["config", "plugins"]).fail(errors.loadModule);
    },
    unlink: function(mod) {},
    ready: function(mods) {
      log.moat(1);
      log.white("Found " + (log.color.green(mods.length)) + " modules!");
      log.moat(1);
      return Promise.all(mods, function(mod) {
        return mod.load(["config", "plugins"]).fail(errors.loadModule);
      }).then(function() {
        log.moat(1);
        log.gray("Watching files...");
        return log.moat(1);
      });
    }
  });
  return Promise.defer().promise;
};

errors = {};

errors.loadModule = function(error) {
  if (/^Missing config file:/.test(error.message)) {
    return;
  }
  throw error;
};
