// Generated by CoffeeScript 1.12.4
var errors;

exports.watch = function() {
  var watcher;
  log.moat(1);
  log.white("Crawling: ");
  log.yellow(lotus.path);
  log.moat(1);
  watcher = lotus.watchModules(lotus.path);
  watcher.on("add", function(mod) {
    return mod.load(["config", "plugins"]).fail(errors.loadModule);
  });
  watcher.on("unlink", function(mod) {
    return log.warn("Module was deleted, but went unhandled: '" + mod.path + "'");
  });
  watcher.on("ready", function(mods) {
    var green;
    green = log.color.green;
    log.moat(1);
    log.white("Found " + (green(mods.length)) + " modules!");
    log.moat(1);
    return Promise.all(mods, function(mod) {
      return mod.load(["config", "plugins"]).fail(errors.loadModule);
    }).then(function() {
      log.moat(1);
      log.gray("Watching files...");
      return log.moat(1);
    });
  });
  return Promise.defer().promise;
};

errors = {};

errors.loadModule = function(error) {
  if (/^Missing config file:/.test(error.message)) {
    return;
  }
  throw error;
};
