// Generated by CoffeeScript 1.12.7
module.exports = {
  loadGlobals: function() {
    return require("./global");
  },
  loadCommands: function() {
    return require("./cli");
  },
  loadModuleMixin: function() {
    return require("./Module");
  }
};
