// Generated by CoffeeScript 1.12.7
var LazyVar, Type, mixin;

LazyVar = require("LazyVar");

Type = require("Type");

mixin = Type.Mixin();

mixin.defineMethods({
  watch: (function() {
    var FileWatcher;
    FileWatcher = LazyVar(function() {
      return require("./FileWatcher");
    });
    return function(patterns, options) {
      if (options == null) {
        options = {};
      }
      options.cwd = this.path;
      return FileWatcher.call(patterns, options);
    };
  })()
});

module.exports = mixin.apply;
